url: https://centymentaylia.github.io
baseurl: /agency/

# Site settings
title: Creative Age Network
email: kp@example.com
description: "The Creatuve Age Network is..."


# Team names, titles and social links
people:
- name: Kerrin Paterson
  pic: 1
  position: Founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #

- name: Rob Paterson
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url:
  - title: facebook
    url:

# Postal address (add as many lines as necessary)
address:
  - line: Blaxland East
  - line: NSW Australia

# Build settings
markdown: kramdown
permalink: pretty
